server:
  port: 8088
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:log4jdbc:h2:mem:jpademo;MODE=MySQL;DATABASE_TO_LOWER=TRUE;
    username: root
    password: root
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    show-sql: true
    properties: # property 사용 설정
      hibernate: # hibernate property 설정
        show_sql: true
        format_sql: true
    hibernate: # hibernate 사용 설정
      ddl-auto: none # 애플리케이션 실행 시점에 테이블 재생성